url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Klingklangflut
lang: 'de-DE'

include:
  - _webpack
exclude:
  - .sass-cache/
  - .jekyll-cache/
#  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
 # - vendor/bundle/
 # - vendor/cache/
 # - vendor/gems/
 # - vendor/ruby/
