title: Klingklangflut
lang: 'de-DE'

include:
  - _webpack
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - package.json
  - package-lock.json
  - webpack.config.js
  - yarn.lock


# the following settings are overwritten when starting the development server with 
# `yarn run develop` and are only used for the build (for Github pages)
url: '' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '/klingklangflut-seite/docs' # the subpath of your site, e.g. /blog
destination: 'docs'
